spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    thread:
      thread-size: 8
